import Head from 'next/head'
import { XStack } from 'tamagui'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aleph Reader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <XStack></XStack>
      </main>
    </>
  )
}
