CREATE TABLE episodes (
  link VARCHAR(1000) NOT NULL PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  pubDate VARCHAR(100) NOT NULL,
  cover VARCHAR(300) NOT NULL,
  podurl VARCHAR(1000) NOT NULL,
  guid VARCHAR(100) NOT NULL,
  title VARCHAR(300) NOT NULL,
  feedid VARCHAR(36) NOT NULL,
  description VARCHAR(3000),
  readed BOOLEAN NOT NULL DEFAULT FALSE,
  starred BOOLEAN NOT NULL DEFAULT FALSE
);