CREATE TABLE feeds (
  url VARCHAR(200) NOT NULL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  favicon VARCHAR(100) NOT NULL,
  language VARCHAR(10),
  deleted INTEGER NOT NULL DEFAULT 0,
  type INTEGER NOT NULL DEFAULT 0
);